"""Fast mode: the real agents on a smaller scope, derived from lab.yaml (never a hand-kept copy).

    python -m sparklab.fastlab --out lab.fast.yaml [--model <id>]   # then: omnigent run lab.fast.yaml
    SPARK_LAB_MODE=fast [SPARK_FAST_MODEL=<id>] python -m sparklab.api   # the UI's "Start the lab" uses it

Same agents, tools, gates and hard rules as lab.yaml; only the breadth shrinks: at most 3 anomalies,
the skeptic attacks the top 3, and the debate is one round. The skeptic still runs check_definitions on
EVERY board expectation (the seeded control must still be caught). --model pins every executor's model
(the id must exist for the provider set up with `omnigent setup`); without it nothing is pinned.
The agent keeps the name spark_lab, so the API and the UI match its sessions as usual.
"""
import argparse
import copy
import os
from pathlib import Path

import yaml

from sparklab import config as C

FAST_NOTES = {
    None: """
FAST MODE (a quicker run of the full loop; the rules and human gates above are unchanged, only the scope is smaller):
- S: ask the scout for at most 3 data-vs-data anomalies.
- A: the skeptic still runs check_definitions on EVERY board expectation first. Then ONE debate round:
  the skeptic attacks the chosen anomaly and the draft with at most 3 points, the experimenter answers each point
  once, then you rule on every point. No reply round: a point still contested takes the conservative option.
- Keep briefs and status lines short.""",
    "scout": """
FAST MODE: compute_surprise for every board expectation as usual, then at most 6 estimate calls and at most
3 anomalies (one ledger entry each). Stop once the 3 are logged.""",
    "skeptic": """
FAST MODE: check_definitions on EVERY board expectation (never skip this). Beyond that, at most 3 attacks per
brief, at most 2 checks per attack. Reply to a rebuttal only if the Supervisor asks you to.""",
    "experimenter": """
FAST MODE: exactly 2 hypotheses plus H_measurement_error; at most 6 estimate calls to derive the floor;
answer each attack once, in one note per attack.""",
}


def fast_spec(model: str | None = None, base: Path | None = None) -> dict:
    spec = copy.deepcopy(yaml.safe_load((base or C.PACKAGE_ROOT / "lab.yaml").read_text()))
    spec["description"] = spec.get("description", "") + " (fast mode)"
    spec["prompt"] = spec["prompt"].rstrip() + "\n" + FAST_NOTES[None].lstrip("\n") + "\n"
    if model:
        spec.setdefault("executor", {})["model"] = model
    for name, note in FAST_NOTES.items():
        if name is None:
            continue
        agent = spec["tools"][name]
        agent["prompt"] = agent["prompt"].rstrip() + "\n" + note.lstrip("\n") + "\n"
        if model:
            agent.setdefault("executor", {})["model"] = model
    return spec


class _Dumper(yaml.SafeDumper):
    pass


_Dumper.add_representer(str, lambda d, s: d.represent_scalar("tag:yaml.org,2002:str", s, style="|" if "\n" in s else None))


def write_fast_spec(dest: Path, model: str | None = None) -> Path:
    dest.write_text("# GENERATED by `python -m sparklab.fastlab` from lab.yaml. Do not edit; edit lab.yaml.\n"
                    + yaml.dump(fast_spec(model), Dumper=_Dumper, sort_keys=False, width=120, allow_unicode=True))
    return dest


def mode() -> str:
    return "fast" if os.environ.get("SPARK_LAB_MODE", "").lower() == "fast" else "full"


def main(argv=None):
    ap = argparse.ArgumentParser(description="Write the fast-mode lab spec derived from lab.yaml.")
    ap.add_argument("--out", default=str(C.PACKAGE_ROOT / "lab.fast.yaml"))
    ap.add_argument("--model", default=os.environ.get("SPARK_FAST_MODEL") or None,
                    help="pin this model on every executor (default: not pinned)")
    a = ap.parse_args(argv)
    out = write_fast_spec(Path(a.out), a.model)
    print(f"Wrote {out}" + (f" (model {a.model})" if a.model else " (model not pinned)"))
    print(f"Run: omnigent run {out.name}")


if __name__ == "__main__":
    main()
